name: Release
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build the app
        run: npm run build
      - name: Run unit tests
        run: npm run test
      - name: Setup environment variables for e2e tests
        run: |
          echo "NODE_ENV=production" >> .env
          echo "API_DOMAIN=localhost" >> .env
          echo "PORT=3000" >> .env
          echo "CORS_ORIGINS=http://localhost,http://localhost:3000" >> .env
      - name: Run e2e tests
        run: npm run test:e2e
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx semantic-release
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: |
            dist
